name: github pages
on:
  issues:
      types: [opened, edited, milestoned]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
            yarn 
            TOKEN=${AUTH_TOKEN} yarn run start
        env:
          AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: |
            cd ./docs
            yarn
            yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/dist
